import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { ReactQueryClientProvider } from "@/components/ClientQueryProvider";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${inter.className}bg-background`}>
        <ReactQueryClientProvider>
        <div className="flex flex-col">
          <main className="flex-1">
            {children}
          </main>
          <ToastContainer />
          </div>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
